name: recommendation-system
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.6.7
- pandas=0.25.1
- pyarrow=0.15.0
- matplotlib=2.2.2
- scipy=1.3.1
- numpy=1.17.0
- seaborn=0.8.1
- scikit-learn=0.21.2
- pytorch=1.2.0
- tensorboardx=1.6
- luigi=2.7.5
- tqdm=4.33
- requests=2.18.4
- jupyterlab=1.0.2
- ipywidgets=7.5.1
- diskcache=3.0.6
- pillow=6.0.0
- pyspark=2.4.3
- psutil=5.2.2
- pip
- category_encoders
- plotly=4.4.1
- pip:
  - imbalanced-learn==0.4.3
  - torchbearer==0.5.1
  - pytorch-nlp==0.4.1
  - unidecode==1.1.1
  - streamlit==0.52.2
  - gym==0.15.4