name: recommendation-system
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.6.5
- pandas=0.24.2
- matplotlib=2.2.2
- scipy=1.1.0
- numpy=1.14.3
- seaborn=0.8.1
- scikit-learn=0.21.2
- pytorch=1.0.1
- tensorboardx=1.6
- luigi=2.7.5
- tqdm=4.23.0
- requests=2.18.4
- jupyterlab=0.32.1
- diskcache=3.0.6
- pillow=6.0.0
- pyspark=2.4.3
- psutil=5.2.2
- pip
- pip:
  - imbalanced-learn==0.4.3
#  - torchbearer==0.3.2
  - lib/torchbearer-1.0.0.dev0-py3-none-any.whl
  - mlflow==1.0.0